name: Simple CI

on:
  push:
    branches:
      -main
      -production

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello! GitHub Actions is working!"